
const { stdout, stderr } = process;


stdout.write('yarn run v1.22.19 \n')
stdout.write('$ cdk deploy --outputs-file ./cdk-outputs.json \n')
stdout.write('\n')
stderr.write('✨  Synthesis time: 5.19s \n')
stdout.write('\n')
stderr.write('reggae-media-stack: deploying... [1/1] \n')
stdout.write('\n')
stderr.write('✅  reggae-media-stack (no changes) \n')
stdout.write('\n')
stderr.write('✨  Deployment time: 0.75s \n')
stdout.write('\n')
stderr.write('Outputs: \n')
stderr.write('reggae-media-stack.articles = reggae-media-stack-reggaemediaarticles6A634E18-1DZ4TBGOYD0SP \n')
stderr.write('reggae-media-stack.bucket = reggae-media-stack-reggaemediastorage909178cb-f8n9sp2jd6gy \n')
stderr.write('reggae-media-stack.settings = reggae-media-stack-reggaemediasettings65EE83D3-19VKLY270KD8I \n')
stderr.write('reggae-media-stack.userPoolClientId = 3s0vtjec82ock37e8sang486r6 \n')
stderr.write('reggae-media-stack.userPoolClientSecret = 7c1hui1soagfrkk0kg6dic4bn8shk0appk5445v6eqvbqko8d0 \n')
stderr.write('reggae-media-stack.userPoolId = eu-west-2_Mwvf2vutj \n')
stdout.write('\n')
stderr.write('Stack ARN: \n')
stdout.write('\n')
stdout.write('arn:aws:cloudformation:eu-west-2:473144555196:stack/reggae-media-stack/a0dc5280-5eb1-11ee-ba74-0a4e05dcb758 \n')
stdout.write('\n')
stderr.write('✨  Total time: 5.94s \n')
stdout.write('\n')
stderr.write('Done in 9.53s. \n')